blank_issues_enabled: true
contact_links:
  - name: ğŸ“„ Docs
    url: https://github.com/Soju06/python-kis/wiki
    about: PyKis ë¼ì´ë¸ŒëŸ¬ë¦¬ì˜ ë¬¸ì„œ
  - name: ğŸ“„ í•œêµ­íˆ¬ìì¦ê¶Œ API ë¬¸ì„œ
    url: https://apiportal.koreainvestment.com/apiservice/oauth2
    about: ë¼ì´ë¸ŒëŸ¬ë¦¬ì—ì„œ ì§€ì›í•˜ì§€ ì•ŠëŠ” ê¸°ëŠ¥ì„ ì°¾ê³  ê³„ì‹ ê°€ìš”?
  - name: ğŸ’¬ í•œêµ­íˆ¬ìì¦ê¶Œ API í¬ëŸ¼
    url: https://apiportal.koreainvestment.com/community
    about: PyKis ì»¤ë®¤ë‹ˆí‹° ë¼ì´ë¸ŒëŸ¬ë¦¬ê°€ ì•„ë‹Œ, í•œêµ­íˆ¬ìì¦ê¶Œì˜ APIì— ë¬¸ì˜í•˜ê³  ì‹¶ìœ¼ì‹ ê°€ìš”?
